project:
  version: "1.2.7"
  env_name: "LunarLander-v3"
  seed: 0

save_parameters:
  run_name: "Replay_and_TargetNetwork_experiment"

network:
  input_size: 8
  output_size: 4
  hidden_size: [128, 128]

agent:
  buffer_size: 100000
  batch_size: 128
  gamma: 0.99
  tau: 0.005 # overrun by the tau scheduler
  lr: 0.001 # overrun by the lr scheduler
  update_every: 4
  DQN_type: "DQN"
  use_replay_buffer: true
  use_target_network: true

training:
  n_episodes: 2500
  max_t: 1000
  eps_start: 1.0
  eps_end: 0.01
  eps_decay: 0.999
  win_condition: 200.0

  # Learning Rate Scheduler
  lr_start: 0.001      # Initial learning rate
  lr_end: 0.0001        # Minimum learning rate
  lr_decay: 0.998       # Multiplicative decay factor per episode: 0.999 translates to one order of magnitude per 2000 episodes
  
  # Tau Scheduler: the smaller, the slower it updates the target network
  tau_start: 0.005       # Initial tau for soft update
  tau_end: 0.0005        # Minimum tau
  tau_decay: 0.999      # Multiplicative decay factor per episode: 0.999 translates to one order of magnitude per 2000 episodes

experiment:
  seeds: [0, 1, 2, 3]
  n_episodes: 3000

ablation_study:
  # The default (when sweep.enable=false), it runs a comaprison of buffer/no_buffer and target/no_target.
  ablation_name: "SeplayBuffer_and_TargetNetwork_SingleRun"
  seeds: [0]
  n_episodes: 2000
  sweep:
    enabled: false
    # Sweep over a single parameter.
    # The parameter path is dot-separated from the root of the config.
    parameter: "agent.buffer_size"
    list_values: [0, 10, 100, 1000, 10000]

lunar_params:
  gravity: -10.0
  is_wind: true
  wind: 8.0        # should be between 0.0 and 20.0 
  turbulence: 1.0  # should be between 0.0 and 2.0