project:
  version: "1.3.1"
  seed: 0

active_env: "LunarLander-v3" 

save_parameters:
  run_name: "SAVE_NAME"
  n_gifs: 5
  show_plots: false # Set to true to display plots, false to only save them
  add_saliency_to_gif: true # Set to true to add a saliency plot to the GIF

environments:
  "LunarLander-v3":
    state_size: 8
    action_size: 4
    win_condition: 200.0
    network:
      hidden_size: [64, 64]
    state_labels: ['X-pos', 'Y-pos', 'X-vel', 'Y-vel', 'Angle', 'Ang-vel', 'Leg1', 'Leg2']
    action_labels: ['No-Op', 'Left', 'Main', 'Right']
    use_fake_actions: false
    num_fake_actions: 16
    sparse_reward: false
      
    lunar_params:
      gravity: -10.0
      enable_wind: false
      wind_power: 5.0
      turbulence_power: 1.5

  "Acrobot-v1":
    state_size: 6
    action_size: 3
    win_condition: -100.0
    network:
      hidden_size: [64, 64]

  "CartPole-v1":
    state_size: 4
    action_size: 2
    win_condition: 475.0
    network:
      hidden_size: [32, 32]

  "MountainCar-v0":
    state_size: 2
    action_size: 3
    win_condition: -110.0 # Solved is avg score of -110.0 over 100 consecutive trials.
    network:
      hidden_size: [64, 64]

  # NOTE: The environments below have CONTINUOUS action spaces.
  # The current DQN agent is designed for DISCRETE actions and will NOT work.
  # An algorithm like DDPG or SAC would be required.
  "Pendulum-v1":
    state_size: 3
    action_size: 1 # Continuous action space with 1 dimension
    win_condition: -150.0
    network:
      hidden_size: [64, 64]

  "BipedalWalker-v3":
    state_size: 24
    action_size: 4 # Continuous action space with 4 dimensions
    win_condition: 300.0
    network:
      hidden_size: [256, 256]

agent:
  buffer_size: 50000
  batch_size: 128
  gamma: 0.99
  tau: 0.005 # overrun by the tau scheduler
  lr: 0.005 # overrun by the lr scheduler
  update_every: 4 # For Acrobot, a smaller value like 1 might be better
  DQN_type: "DDQN" # This will be overridden by the ablation study
  use_replay_buffer: true
  use_target_network: true
  is_dueling: true

training:
  n_episodes: 500
  max_t: 1000
  eps_start: 1.0
  eps_end: 0.001
  eps_decay: 0.99 # Multiplicative decay factor per episode: 0.999 translates to one order of magnitude per 2000 episodes

  # Learning Rate Scheduler
  lr_start: 0.005      # Initial learning rate
  lr_end: 0.0005        # Minimum learning rate
  lr_decay: 0.998       # Multiplicative decay factor per episode: 0.999 translates to one order of magnitude per 2000 episodes
  
  # Tau Scheduler: the smaller, the slower it updates the target network
  tau_start: 0.005       # Initial tau for soft update
  tau_end: 0.0005        # Minimum tau
  tau_decay: 0.999      # Multiplicative decay factor per episode: 0.999 translates to one order of magnitude per 2000 episodes

experiment:
  seeds: [0, 1, 2, 3]
  n_episodes: 3000

ablation_study:
  study_type: "sweep" # Can be :
  # 'component' - to ablate specific components of the DQN algorithm, like the replay buffer or target network,
  # 'sweep' - to sweep a specific hyperparameter across a range of values,
  # 'dqn_variants' - to compare different DQN variants (DQN no target, DQN, Double DQN, Dueling DQN) under the same conditions.
  ablation_name: "Dueling_vs_DQN_NoWind_64x64Net_epsDecay_NoDummies"
  seeds: [0] # Using a few seeds will give more robust results
  n_episodes: 1500 # Increased episodes as the problem is harder
  sweep:
    enabled: true
    parameter: "agent.is_dueling"
    list_values: [false, true]